[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
common = { workspace = true }
iced = {version = "0.13.1",features = ["tokio","image"]} 

