[workspace]
resolver = "2"
members = [ "client", "common","server",]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1.43.0" }
common = {path = "./common"}
serde = "1"

